---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bravo
  namespace: default
  labels:
    {{- include "components.labels" . | nindent 4 }}
    gwcp.guidewire.com/app-name: bravo
    gwcp.guidewire.com/tenant-name: quadrant-shared
    gwcp.guidewire.com/version: '6.5.1'
    gwcp.guidewire.com/created-by: pod-avondale
    gwcp.guidewire.com/maintained-by: pod-avondale
    gwcp.guidewire.com/dept: {{ .Values.departmentCode | quote }}
spec:
  interval: 10m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bravo
  namespace: default
  labels:
    {{- include "components.labels" . | nindent 4 }}
    gwcp.guidewire.com/app-name: bravo
    gwcp.guidewire.com/tenant-name: quadrant-shared
    gwcp.guidewire.com/version: '6.5.1'
    gwcp.guidewire.com/created-by: pod-avondale
    gwcp.guidewire.com/maintained-by: pod-avondale
    gwcp.guidewire.com/dept: {{ .Values.departmentCode | quote }}
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bravo
      version: '6.5.1'
  interval: 10m0s
  values: {{ toYaml .Values.bravo.values | nindent 4 }}
